import art1 from "./assets/images/mak.png";

export const sampleAuthors = [
  {
    id: 1,
    name: "Jan Pan",
    country: "Polska",
  },
  {
    id: 2,
    name: "Apranam Vanman",
    country: "Gujana",
  },
  {
    id: 3,
    name: "Jurgis Ginter",
    country: "Norwegia",
  },
  {
    id: 4,
    name: "Falconer Merit",
    country: "Niemcy",
  },
  {
    id: 5,
    name: "Hipolit Litwin",
    country: "Polska",
  },
  {
    id: 6,
    name: "Pikolino Mikron",
    country: "Argentyna",
  },
];

export const sampleArts = [
  {
    id: 1,
    title: "Obraz 1",
    author: sampleAuthors[0],
    date: Date("11-05-2020"),
    bookId: 1,
    owner: "Galeria EL",
    createDate: "lata 90",
    description:
      "Occaecat amet cillum nisi labore culpa. Ullamco ea nisi sint anim culpa cupidatat culpa amet dolore Lorem. Sunt officia cupidatat reprehenderit reprehenderit est sit. Esse cupidatat eiusmod laboris dolore dolore commodo nulla esse incididunt. Deserunt nostrud adipisicing anim laborum non minim amet. Pariatur sint commodo pariatur dolor. In minim pariatur aute dolor.",
    style: "modern",
    technique: "malarstwo",
    type: "obraz",
    amount: 1,
    partTittles: null,
    measurements: "112x302",
    value: "100020",
    purchaseDate: Date("09-02-2009"),
    purchaseSource: "Dom aukcyjny",
    purchaseWay: "aukcja",
    comment: null,
    photo: art1,
  },
  {
    id: 2,
    title: "Obraz 2",
    author: sampleAuthors[1],
    date: Date("21-05-2019"),
    bookId: 1,
    owner: "Galeria EL",
    createDate: "lata 90",
    description:
      "Occaecat amet cillum nisi labore culpa. Ullamco ea nisi sint anim culpa cupidatat culpa amet dolore Lorem. Sunt officia cupidatat reprehenderit reprehenderit est sit. Esse cupidatat eiusmod laboris dolore dolore commodo nulla esse incididunt. Deserunt nostrud adipisicing anim laborum non minim amet. Pariatur sint commodo pariatur dolor. In minim pariatur aute dolor.",
    style: "modern",
    technique: "malarstwo",
    type: "obraz",
    amount: 1,
    partTittles: null,
    measurements: "112x302",
    value: "100020",
    purchaseDate: Date("09-02-2009"),
    purchaseSource: "Dom aukcyjny",
    purchaseWay: "aukcja",
    comment: null,
    photo: art1,
  },
  {
    id: 3,
    title: "Obraz 3",
    author: sampleAuthors[2],
    date: Date("11-05-2020"),
    bookId: 1,
    owner: "Galeria EL",
    createDate: "lata 90",
    description:
      "Occaecat amet cillum nisi labore culpa. Ullamco ea nisi sint anim culpa cupidatat culpa amet dolore Lorem. Sunt officia cupidatat reprehenderit reprehenderit est sit. Esse cupidatat eiusmod laboris dolore dolore commodo nulla esse incididunt. Deserunt nostrud adipisicing anim laborum non minim amet. Pariatur sint commodo pariatur dolor. In minim pariatur aute dolor.",
    style: "modern",
    technique: "malarstwo",
    type: "obraz",
    amount: 1,
    partTittles: null,
    measurements: "112x302",
    value: "100020",
    purchaseDate: Date("09-02-2009"),
    purchaseSource: "Dom aukcyjny",
    purchaseWay: "aukcja",
    comment: null,
    photo: art1,
  },
  {
    id: 4,
    title: "Obraz 4",
    author: sampleAuthors[3],
    date: Date("11-05-2020"),
    bookId: 1,
    owner: "Galeria EL",
    createDate: "lata 90",
    description:
      "Occaecat amet cillum nisi labore culpa. Ullamco ea nisi sint anim culpa cupidatat culpa amet dolore Lorem. Sunt officia cupidatat reprehenderit reprehenderit est sit. Esse cupidatat eiusmod laboris dolore dolore commodo nulla esse incididunt. Deserunt nostrud adipisicing anim laborum non minim amet. Pariatur sint commodo pariatur dolor. In minim pariatur aute dolor.",
    style: "modern",
    technique: "malarstwo",
    type: "obraz",
    amount: 1,
    partTittles: null,
    measurements: "112x302",
    value: "100020",
    purchaseDate: Date("09-02-2009"),
    purchaseSource: "Dom aukcyjny",
    purchaseWay: "aukcja",
    comment: null,
    photo: art1,
  },
  {
    id: 5,
    title: "Obraz 5",
    author: sampleAuthors[4],
    date: Date("11-05-2020"),
    bookId: 1,
    owner: "Galeria EL",
    createDate: "lata 90",
    description:
      "Occaecat amet cillum nisi labore culpa. Ullamco ea nisi sint anim culpa cupidatat culpa amet dolore Lorem. Sunt officia cupidatat reprehenderit reprehenderit est sit. Esse cupidatat eiusmod laboris dolore dolore commodo nulla esse incididunt. Deserunt nostrud adipisicing anim laborum non minim amet. Pariatur sint commodo pariatur dolor. In minim pariatur aute dolor.",
    style: "modern",
    technique: "malarstwo",
    type: "obraz",
    amount: 1,
    partTittles: null,
    measurements: "112x302",
    value: "100020",
    purchaseDate: Date("09-02-2009"),
    purchaseSource: "Dom aukcyjny",
    purchaseWay: "aukcja",
    comment: null,
    photo: art1,
  },
  {
    id: 6,
    title: "Obraz 6",
    author: sampleAuthors[5],
    date: Date("11-05-2020"),
    bookId: 1,
    owner: "Galeria EL",
    createDate: "lata 90",
    description:
      "Occaecat amet cillum nisi labore culpa. Ullamco ea nisi sint anim culpa cupidatat culpa amet dolore Lorem. Sunt officia cupidatat reprehenderit reprehenderit est sit. Esse cupidatat eiusmod laboris dolore dolore commodo nulla esse incididunt. Deserunt nostrud adipisicing anim laborum non minim amet. Pariatur sint commodo pariatur dolor. In minim pariatur aute dolor.",
    style: "modern",
    technique: "malarstwo",
    type: "obraz",
    amount: 1,
    partTittles: null,
    measurements: "112x302",
    value: "100020",
    purchaseDate: Date("09-02-2009"),
    purchaseSource: "Dom aukcyjny",
    purchaseWay: "aukcja",
    comment: null,
    photo: art1,
  },
];
